### PR TITLE
Add sender name to message & small fixes

### LINKED ISSUE #15: Additional message info
Add sender and chat to mesage text when resending (something like `username@chat` in the beginning of the message)

### PR DESCRIPTION
**Pull request by Pelmenner**
Messages are currently sent individually, and VK chat names are not displayed
In TG one image with text now works properly
Closes #15

### CODE REVIEW

File: messenger.go [hunk 1]
```diff
@@ -292,6 +304,16 @@ func (m *TGMessenger) ProcessMessage(message *tgbotapi.Message, chat *Chat) {
...
 }
 
+func (m *VKMessenger) getSenderName(message object.MessagesMessage) string {
+	userResponse, err := m.vk.UsersGet(api.Params{"user_ids": message.FromID})
+	if err != nil {
+		log.Print("could not find vk user with id ", message.FromID, err)
+		return ""
+	}
+	// have not found a way to get chat name
+	return concatenateMessageSender(userResponse[0].FirstName+" "+userResponse[0].LastName, "vk")
```
Comment (Mad-Proger) [inline messenger.go:314]: we still cannot get vk chat name, can we?

File: messenger.go [hunk 2]
```diff
@@ -319,17 +341,27 @@ func (m *TGMessenger) ProcessCommand(message *tgbotapi.Message, chat *Chat) {
...
+		log.Print("could not find community with id ", wall.FromID)
+		return ""
+	}
+	return concatenateMessageSender(userResponce[0].Name, "vk")
+}
+
+func (m *VKMessenger) processWall(wall object.WallWallpost, chat *Chat) {
+	message := Message{
+		Text:   wall.Text,
+		Sender: m.getWallAuthor(&wall),
```
Comment (Mad-Proger) [inline messenger.go:356]: i believe we should just use public name instead of chat name. Looks like getting rid of sender name is a bad idea

**Review by Mad-Proger — CHANGES_REQUESTED** [review]

File: messenger.go (hunk 2 above)
Comment (Pelmenner) [reply messenger.go:356]: Sender's name is included in another message, which contains their text, and is normally sent right before the "wall message"

File: messenger.go (hunk 1 above)
Comment (Pelmenner) [reply messenger.go:314]: VK gives an error when trying to call getChat with the chat's id. It would be great if you can solve it, but for now I don't have any ideas

**Review by Mad-Proger — APPROVED** [review]
